services:
  janio-bot:
    build: .
    network_mode: "host"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - janio-data:/app/data
      - /tmp/janiobot:/tmp/janiobot

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    network_mode: "host"
    environment:
      - _JAVA_OPTIONS=-Xmx1G
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - /tmp/janiobot:/tmp/janiobot

volumes:
  janio-data:
